server:
  port: 8088
spring:
  application:
    name: park-server
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/parkinglot?useUnicode=true&characterEncoding=utf8
    username: root
    password: cnm18274003491
eureka:
  instance:
    hostname: localhost
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
