eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8088/eureka/
server:
  port: 8081
spring:
  application:
    name: api-auth
  datasource:
      url: jdbc:mysql://127.0.0.1:3306/parkinglot?useUnicode=true&characterEncoding=utf8
      username: root
      password: cnm18274003491
  jackson:
    date-format: yyyy-MM-dd
    time-zone: GMT+8
  redis:
    host: localhost
    password: 123456
    port: 6379
    database: 0
    jedis:
      pool:
        max-active: 8
        max-idle: 8
        max-wait: -1ms
        min-idle: 0
logging:
  level:
    cn:
     park:
      mapper: debug
mybatis:
  mapper-locations: classpath*:cn/**/mapper/*.xml