eureka:
  client:
    service-url:
      defaultZone: http://localhost:8088/eureka/
server:
  port: 8089
spring:
  application:
    name: park-zuul
ribbon:
    ReadTimeout: 60000
    ConnectTimeout: 60000
zuul:
  routes:
    api-admin: /api-admin/**
    api-auth: /api-auth/**
    api-search: /api-search/**