server:
  port: 8082
spring:
  #application:
    #name: api-search
  datasource:
    url: jdbc:mysql:///parkinglot?useUnicode=true&characterEncoding=utf8
    username: root
    password: root
  data:
    elasticsearch:
      cluster-nodes: 127.0.0.1:9300
      cluster-name: elasticsearch
      repositories:
        enabled: true

